export const dataFixes = [
    {
        videoThumnail: "/assets/videoImage/vedioImg1.png",
        ownerimage: "/assets/videoImage/videouser1.png",
        ownername: "Ram kumar something",
        duration: "5",
        views: "1657",
        description: "Half dim Backlight (got black spot at the bottom of the screen)Half dim Backlight (got black spot at the bottom of. ",
        type: "Fix",
    },
    {
        videoThumnail: "/assets/videoImage/vedioImg1.png",
        ownerimage: "/assets/videoImage/videouser1.png",
        ownername: "Ram kumar something",
        duration: "5",
        views: "1657",
        description: "Half dim Backlight (got black spot at the bottom of the screen)Half dim Backlight (got black spot at the bottom of. ",
        type: "Fix",
    },
    {
        videoThumnail: "/assets/videoImage/vedioImg1.png",
        ownerimage: "/assets/videoImage/videouser1.png",
        ownername: "Ram kumar something",
        duration: "5",
        views: "1657",
        description: "Half dim Backlight (got black spot at the bottom of the screen)Half dim Backlight (got black spot at the bottom of. ",
        type: "Fix",
    },
    {
        videoThumnail: "/assets/videoImage/vedioImg1.png",
        ownerimage: "/assets/videoImage/videouser1.png",
        ownername: "Ram kumar something",
        duration: "5",
        views: "1657",
        description: "Half dim Backlight (got black spot at the bottom of the screen)Half dim Backlight (got black spot at the bottom of. ",
        type: "Fix",
    },
    {
        videoThumnail: "/assets/videoImage/vedioImg1.png",
        ownerimage: "/assets/videoImage/videouser1.png",
        ownername: "Ram kumar something",
        duration: "5",
        views: "1657",
        description: "Half dim Backlight (got black spot at the bottom of the screen)Half dim Backlight (got black spot at the bottom of. ",
        type: "Fix",
    },
    {
        videoThumnail: "/assets/videoImage/vedioImg1.png",
        ownerimage: "/assets/videoImage/videouser1.png",
        ownername: "Ram kumar something",
        duration: "5",
        views: "1657",
        description: "Half dim Backlight (got black spot at the bottom of the screen)Half dim Backlight (got black spot at the bottom of. ",
        type: "Fix",
    },
    {
        videoThumnail: "/assets/videoImage/vedioImg1.png",
        ownerimage: "/assets/videoImage/videouser1.png",
        ownername: "Ram kumar something",
        duration: "5",
        views: "1657",
        description: "Half dim Backlight (got black spot at the bottom of the screen)Half dim Backlight (got black spot at the bottom of. ",
        type: "Fix",
    },
    {
        videoThumnail: "/assets/videoImage/vedioImg1.png",
        ownerimage: "/assets/videoImage/videouser1.png",
        ownername: "Ram kumar something",
        duration: "5",
        views: "1657",
        description: "Half dim Backlight (got black spot at the bottom of the screen)Half dim Backlight (got black spot at the bottom of. ",
        type: "Fix",
    },
    {
        videoThumnail: "/assets/videoImage/vedioImg1.png",
        ownerimage: "/assets/videoImage/videouser1.png",
        ownername: "Ram kumar something",
        duration: "5",
        views: "1657",
        description: "Half dim Backlight (got black spot at the bottom of the screen)Half dim Backlight (got black spot at the bottom of. ",
        type: "Fix",
    },

  ]

export const dataFlicks = [
    {
        videoThumnail: "/assets/videoImage/vedioImg1.png",
        ownerimage: "/assets/videoImage/videouser1.png",
        ownername: "Ram kumar something",
        duration: "5",
        views: "1657",
        description: "Half dim Backlight (got black spot at the bottom of the screen)Half dim Backlight (got black spot at the bottom of. ",
        type: "Flick",
    },
    {
        videoThumnail: "/assets/videoImage/vedioImg1.png",
        ownerimage: "/assets/videoImage/videouser1.png",
        ownername: "Ram kumar something",
        duration: "5",
        views: "1657",
        description: "Half dim Backlight (got black spot at the bottom of the screen)Half dim Backlight (got black spot at the bottom of. ",
        type: "Flick",
    },
    {
        videoThumnail: "/assets/videoImage/vedioImg1.png",
        ownerimage: "/assets/videoImage/videouser1.png",
        ownername: "Ram kumar something",
        duration: "5",
        views: "1657",
        description: "Half dim Backlight (got black spot at the bottom of the screen)Half dim Backlight (got black spot at the bottom of. ",
        type: "Flick",
    },
    {
        videoThumnail: "/assets/videoImage/vedioImg1.png",
        ownerimage: "/assets/videoImage/videouser1.png",
        ownername: "Ram kumar something",
        duration: "5",
        views: "1657",
        description: "Half dim Backlight (got black spot at the bottom of the screen)Half dim Backlight (got black spot at the bottom of. ",
        type: "Flick",
    },
    {
        videoThumnail: "/assets/videoImage/vedioImg1.png",
        ownerimage: "/assets/videoImage/videouser1.png",
        ownername: "Ram kumar something",
        duration: "5",
        views: "1657",
        description: "Half dim Backlight (got black spot at the bottom of the screen)Half dim Backlight (got black spot at the bottom of. ",
        type: "Flick",
    },
    {
        videoThumnail: "/assets/videoImage/vedioImg1.png",
        ownerimage: "/assets/videoImage/videouser1.png",
        ownername: "Ram kumar something",
        duration: "5",
        views: "1657",
        description: "Half dim Backlight (got black spot at the bottom of the screen)Half dim Backlight (got black spot at the bottom of. ",
        type: "Flick",
    },
    {
        videoThumnail: "/assets/videoImage/vedioImg1.png",
        ownerimage: "/assets/videoImage/videouser1.png",
        ownername: "Ram kumar something",
        duration: "5",
        views: "1657",
        description: "Half dim Backlight (got black spot at the bottom of the screen)Half dim Backlight (got black spot at the bottom of. ",
        type: "Flick",
    },
    {
        videoThumnail: "/assets/videoImage/vedioImg1.png",
        ownerimage: "/assets/videoImage/videouser1.png",
        ownername: "Ram kumar something",
        duration: "5",
        views: "1657",
        description: "Half dim Backlight (got black spot at the bottom of the screen)Half dim Backlight (got black spot at the bottom of. ",
        type: "Flick",
    },
    {
        videoThumnail: "/assets/videoImage/vedioImg1.png",
        ownerimage: "/assets/videoImage/videouser1.png",
        ownername: "Ram kumar something",
        duration: "5",
        views: "1657",
        description: "Half dim Backlight (got black spot at the bottom of the screen)Half dim Backlight (got black spot at the bottom of. ",
        type: "Flick",
    },

]

export const Recommended = [
    {
        videoThumnail: "/assets/videoImage/vedioImg1.png",
        ownerimage: "/assets/videoImage/videouser1.png",
        ownername: "Ram kumar something",
        duration: "5",
        views: "1657",
        description: "Half dim Backlight (got black spot at the bottom of the screen)Half dim Backlight (got black spot at the bottom of. ",
        type: "Fix",
    },
    {
        videoThumnail: "/assets/videoImage/vedioImg1.png",
        ownerimage: "/assets/videoImage/videouser1.png",
        ownername: "Ram kumar something",
        duration: "5",
        views: "1657",
        description: "Half dim Backlight (got black spot at the bottom of the screen)Half dim Backlight (got black spot at the bottom of. ",
        type: "Flick",
    },
    {
        videoThumnail: "/assets/videoImage/vedioImg1.png",
        ownerimage: "/assets/videoImage/videouser1.png",
        ownername: "Ram kumar something",
        duration: "5",
        views: "1657",
        description: "Half dim Backlight (got black spot at the bottom of the screen)Half dim Backlight (got black spot at the bottom of. ",
        type: "Fix",
    },
    {
        videoThumnail: "/assets/videoImage/vedioImg1.png",
        ownerimage: "/assets/videoImage/videouser1.png",
        ownername: "Ram kumar something",
        duration: "5",
        views: "1657",
        description: "Half dim Backlight (got black spot at the bottom of the screen)Half dim Backlight (got black spot at the bottom of. ",
        type: "Flick",
    },

    {
        videoThumnail: "/assets/videoImage/vedioImg1.png",
        ownerimage: "/assets/videoImage/videouser1.png",
        ownername: "Ram kumar something",
        duration: "5",
        views: "1657",
        description: "Half dim Backlight (got black spot at the bottom of the screen)Half dim Backlight (got black spot at the bottom of. ",
        type: "Fix",
    },
    {
        videoThumnail: "/assets/videoImage/vedioImg1.png",
        ownerimage: "/assets/videoImage/videouser1.png",
        ownername: "Ram kumar something",
        duration: "5",
        views: "1657",
        description: "Half dim Backlight (got black spot at the bottom of the screen)Half dim Backlight (got black spot at the bottom of. ",
        type: "Fix",
    },
    {
        videoThumnail: "/assets/videoImage/vedioImg1.png",
        ownerimage: "/assets/videoImage/videouser1.png",
        ownername: "Ram kumar something",
        duration: "5",
        views: "1657",
        description: "Half dim Backlight (got black spot at the bottom of the screen)Half dim Backlight (got black spot at the bottom of. ",
        type: "Flick",
    },
    {
        videoThumnail: "/assets/videoImage/vedioImg1.png",
        ownerimage: "/assets/videoImage/videouser1.png",
        ownername: "Ram kumar something",
        duration: "5",
        views: "1657",
        description: "Half dim Backlight (got black spot at the bottom of the screen)Half dim Backlight (got black spot at the bottom of. ",
        type: "Fix",
    },
    {
        videoThumnail: "/assets/videoImage/vedioImg1.png",
        ownerimage: "/assets/videoImage/videouser1.png",
        ownername: "Ram kumar something",
        duration: "5",
        views: "1657",
        description: "Half dim Backlight (got black spot at the bottom of the screen)Half dim Backlight (got black spot at the bottom of. ",
        type: "Flick",
    },
    {
        videoThumnail: "/assets/videoImage/vedioImg1.png",
        ownerimage: "/assets/videoImage/videouser1.png",
        ownername: "Ram kumar something",
        duration: "5",
        views: "1657",
        description: "Half dim Backlight (got black spot at the bottom of the screen)Half dim Backlight (got black spot at the bottom of. ",
        type: "Fix",
    },
    {
        videoThumnail: "/assets/videoImage/vedioImg1.png",
        ownerimage: "/assets/videoImage/videouser1.png",
        ownername: "Ram kumar something",
        duration: "5",
        views: "1657",
        description: "Half dim Backlight (got black spot at the bottom of the screen)Half dim Backlight (got black spot at the bottom of. ",
        type: "Flick",
    },

    {
        videoThumnail: "/assets/videoImage/vedioImg1.png",
        ownerimage: "/assets/videoImage/videouser1.png",
        ownername: "Ram kumar something",
        duration: "5",
        views: "1657",
        description: "Half dim Backlight (got black spot at the bottom of the screen)Half dim Backlight (got black spot at the bottom of. ",
        type: "Fix",
    },
    {
        videoThumnail: "/assets/videoImage/vedioImg1.png",
        ownerimage: "/assets/videoImage/videouser1.png",
        ownername: "Ram kumar something",
        duration: "5",
        views: "1657",
        description: "Half dim Backlight (got black spot at the bottom of the screen)Half dim Backlight (got black spot at the bottom of. ",
        type: "Fix",
    },
    {
        videoThumnail: "/assets/videoImage/vedioImg1.png",
        ownerimage: "/assets/videoImage/videouser1.png",
        ownername: "Ram kumar something",
        duration: "5",
        views: "1657",
        description: "Half dim Backlight (got black spot at the bottom of the screen)Half dim Backlight (got black spot at the bottom of. ",
        type: "Flick",
    },


]